In [2]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,6,8],
    [5,7,9]
])
a.shape

(3, 3)

In [5]:
a.shape

(3, 3)

In [6]:
a.ndim

2

In [7]:
a.dtype

dtype('int32')

In [11]:
a[1,1]

6

In [12]:
a[1] [1]

6

In [13]:
a[:, 0:2]

array([[1, 2],
       [4, 6],
       [5, 7]])

In [9]:
arange = np.arange(5)
arange + 20

array([20, 21, 22, 23, 24])

In [15]:
arange2 = np.arange(5)
print(arange2)
print(type(arange2))
print(arange2 <=3)

[0 1 2 3 4]
<class 'numpy.ndarray'>
[ True  True  True  True False]


In [22]:
import pandas as pd
import numpy as np
g7_pop = pd.Series([23.66, 6.7806, 3.54, 2, 12.543, 8.4235, 5, 1.253]) #Creo una serie pandas, cada valor tiene su índice

In [23]:
g7_pop

0    23.6600
1     6.7806
2     3.5400
3     2.0000
4    12.5430
5     8.4235
6     5.0000
7     1.2530
dtype: float64

In [25]:
g7_pop.name = 'Número de habitantes de 7 países' #Le doy nombre a la serie

In [26]:
g7_pop

0    23.6600
1     6.7806
2     3.5400
3     2.0000
4    12.5430
5     8.4235
6     5.0000
7     1.2530
Name: Número de habitantes de 7 países, dtype: float64

In [29]:
g7_pop.dtype

dtype('float64')

In [35]:
g7_pop.values #Guarda los valores en un array? No debería ser numpy array?

array([23.66  ,  6.7806,  3.54  ,  2.    , 12.543 ,  8.4235,  5.    ,
        1.253 ])

In [36]:
type(g7_pop.values) #En efecto, es un np array

numpy.ndarray

In [37]:
 g7_pop[0]

23.66

In [38]:
g7_pop[1]

6.7806

In [39]:
g7_pop[2]

3.54

In [41]:
g7_pop.index

RangeIndex(start=0, stop=8, step=1)

Podemos darle nuestro propio valor a los índices

In [46]:
g7_pop.index = ['Argentina', 
              'Brasil', 
              'Uruguay',
              'Paraguay', 
              'Chile', 
              'Bolivia', 
              'Perú',
              'Colombia'
             ]

In [47]:
g7_pop

Argentina    23.6600
Brasil        6.7806
Uruguay       3.5400
Paraguay      2.0000
Chile        12.5430
Bolivia       8.4235
Perú          5.0000
Colombia      1.2530
Name: Número de habitantes de 7 países, dtype: float64

Se puede hacer todo esto en un solo paso

In [51]:
g4_pop = pd.Series([10, 4, 5, 3] ,index = ['Canadá', 'Ecuador', 'Puerto Rico', 'Honduras'], name= 'Población de 4 países')

In [52]:
g4_pop

Canadá         10
Ecuador         4
Puerto Rico     5
Honduras        3
Name: Población de 4 países, dtype: int64